"""Editorial library: distinct lifecycle messages and a rotating editing series.

All copy is plain text. newsletter_content owns escaping and presentation.
Prompts are suggestions to review in the studio, not promises of timed results.
"""

LIFECYCLE_FAMILIES = {
    "welcome_activation": ("welcome_activation", "first_prompt", "one_clip_challenge"),
    "first_cut": ("first_cut", "clear_brief"),
    "export_nudge": ("export_nudge", "final_pass", "publishable_cut"),
    "first_export": ("first_export",),
    "dormant": ("dormant", "smaller_comeback", "fresh_angle"),
    "winback": ("winback", "camera_roll", "open_door"),
}

# Each tuple is key, label, subject, preheader, heading, opening paragraphs,
# optional prompt, closing paragraphs, button. Every message has one job.
LIFECYCLE_COPY = [
    (
        "welcome_activation", "Start · 1 / The first clip",
        "Your camera roll has unfinished business",
        "Pick one clip. Give it one instruction. See what changes.",
        "That clip you keep meaning to edit.",
        ["The interview. The product demo. The take you liked until you remembered it needed editing.",
         "Bring one of them into Valmera. Once it has been analysed, tell the editor what you want to change in ordinary words."],
        "Trim the long pauses, keep my meaning, and show me the result.",
        ["Watch the preview. Keep what works. Ask for a different cut where it doesn't. You bring the judgment; Valmera handles the editing steps."],
        "Choose my first clip",
    ),
    (
        "first_prompt", "Start · 2 / A better brief",
        "Steal this first-edit prompt",
        "A clear brief beats staring at an empty chat box.",
        "You don't need editor vocabulary.",
        ["You already know when a video drags, when a caption is hard to read, or when the point arrives too late. That's enough to start.",
         "Upload a talking-head clip, let Valmera analyse it, then try this:"],
        "Make a tighter version of this clip. Remove long pauses, keep the natural delivery, and add readable captions.",
        ["Review the result before exporting. If the pacing feels rushed, say so. A useful second instruction can be as simple as: let that sentence breathe."],
        "Try the prompt",
    ),
    (
        "one_clip_challenge", "Start · 3 / A small challenge",
        "One clip. One point. One finished thing.",
        "Leave the full content plan for later. Start here.",
        "Make the assignment smaller.",
        ["A whole content strategy is a lot to open on a Tuesday. One useful clip is a much easier place to begin.",
         "Choose a short recording with a single idea: an answer, a demonstration, a moment worth keeping. Bring it into Valmera and give the edit a clear destination."],
        "Keep the section that explains the main idea. Cut the setup that isn't needed, and add captions.",
        ["The goal is a version you can watch and improve. One finished thing gives you more to work with than another folder of possibilities."],
        "Start with one clip",
    ),
    (
        "first_cut", "First edit · 1 / Get moving",
        "The first cut can be rough",
        "Your next step is a clear instruction, not a perfect plan.",
        "Give the footage a first direction.",
        ["You've opened a project. Now pick the one thing you'd most like to improve: the pace, the framing, or how easily someone can follow the words.",
         "If your footage is still uploading or being analysed, let that finish first. Then start with a small request:"],
        "Tighten the pauses in this video. Keep the useful details and the way I naturally speak.",
        ["Watch what changed before asking for the next thing. A first cut gives you something concrete to react to."],
        "Make the first cut",
    ),
    (
        "clear_brief", "First edit · 2 / Unstick the brief",
        "“Make it better” needs one more sentence",
        "Tell the editor who is watching and what they should understand.",
        "Give your edit a destination.",
        ["Try finishing this sentence: this video is for ___, and I want them to understand ___.", "That little bit of context helps turn a vague request into an edit you can judge. For a product demonstration, for example:"],
        "This is for someone seeing the product for the first time. Keep the part that shows how it works, trim repeated explanations, and add clear captions.",
        ["Change the brief to fit your footage. Then review the preview against that original goal."],
        "Give my edit a brief",
    ),
    (
        "export_nudge", "Finish · 1 / Leave the drafts",
        "A draft can't meet your audience",
        "Your next move: review the cut, then export a version.",
        "Let this one become a video.",
        ["Your project has an edit in it. Before starting another round of changes, watch it once from beginning to end.",
         "Does the opening get to the point? Can you follow the words? Does the ending feel intentional? Pick the one change that matters most."],
        "Tighten the opening so the main point arrives sooner. Keep the rest of the edit as it is.",
        ["When the preview looks right and the original has finished uploading, use Export and download the finished file."],
        "Review and export",
    ),
    (
        "final_pass", "Finish · 2 / The last pass",
        "Three checks before you hit Export",
        "Sound. Captions. Framing. Give each a quick look.",
        "Watch it like it's someone else's.",
        ["First, listen without looking: is the voice easy to hear? Next, watch without sound: can the captions carry the meaning? Finally, check the framing: is the important action visible?",
         "If one of those feels off, ask for that specific change."],
        "Make the captions easier to read on a phone. Keep them clear of the speaker's face.",
        ["Play the updated preview once more. If it does the job, export a version you can actually use."],
        "Give it a final pass",
    ),
    (
        "publishable_cut", "Finish · 3 / Decide what is done",
        "Give “final_final” an ending",
        "Choose one improvement. Then decide whether this version is ready.",
        "A finish line for this edit.",
        ["There is always another caption style to try. Another beat to trim. Another version to compare.",
         "For this pass, choose one test: does the video communicate what you meant? Fix the part that gets in the way, then stop and watch."],
        None,
        ["If the answer is yes, export the cut. Your next idea deserves some of the attention you've been giving this one."],
        "Finish this version",
    ),
    (
        "first_export", "After export · A second use",
        "One finished video. What else is in it?",
        "A useful answer or a sharp demonstration could become the next clip.",
        "You made something you can share.",
        ["Your first export is complete. Before you put the footage away, think about a second use for it: one answer, one demonstration, one moment that makes sense on its own.",
         "Keep the file you've already downloaded. If you want a different cut, return to the footage with a new brief:"],
        "Find a self-contained section that answers one useful question. Tell me which section you suggest before making changes.",
        ["Review the suggestion, then decide whether it deserves its own edit. A second video can start with a new angle on work you've already done."],
        "Find another angle",
    ),
    (
        "dormant", "Return · 1 / Pick up a thread",
        "An unfinished idea is still an idea",
        "Pick up one thread. You don't need to plan a full comeback.",
        "Come back for one small edit.",
        ["You don't need a new recording session to get moving again. There may already be a useful clip in your projects or camera roll.",
         "Open Valmera and choose something you still care about. Give it a smaller assignment than the one you left it with."],
        "Help me make a shorter, clearer version. Start by suggesting what to keep, and wait for my choice.",
        ["One decision is enough to restart. The rest can follow once you've seen the footage again."],
        "Pick up an idea",
    ),
    (
        "smaller_comeback", "Return · 2 / Remove the big ask",
        "Your next video can be smaller",
        "One answer. One demo. One moment worth sharing.",
        "Leave the big production for later.",
        ["Try an edit with a deliberately small brief: answer one question your audience asks. Show one step that is easier to watch than explain. Keep one moment that made you pause.",
         "Bring the relevant footage into Valmera and work toward that single outcome."],
        "Keep the part that answers the question directly. Trim the repeated setup and add readable captions.",
        ["A focused clip is a useful reason to open the studio again. You can build from there."],
        "Make a focused clip",
    ),
    (
        "fresh_angle", "Return · 3 / Change the audience",
        "Same footage. A different person watching.",
        "A new audience can give an old recording a fresh brief.",
        "Who hasn't heard this yet?",
        ["The explanation you recorded for a customer might help a first-time buyer. A long conversation might contain the answer a beginner needs.",
         "Choose a recording and change the person you're making the edit for. That often makes the next cut easier to see."],
        "Make this easier for a beginner to follow. Keep the explanation and its example together, and remove tangents.",
        ["Review the edit through that person's eyes. Keep the details they need to understand the point."],
        "Try a new brief",
    ),
    (
        "winback", "Reconnect · 1 / A concrete reason",
        "Bring the video you kept putting off",
        "Start with the part that made the edit feel like work.",
        "What stopped this one from getting made?",
        ["Too much dead air? A long introduction? Captions you didn't want to place by hand? Start there.",
         "Valmera lets you describe the change in chat, review a preview, and refine the result. You don't have to solve the whole video in your first message."],
        "Trim the slow setup, keep the useful explanation, and show me a first cut to review.",
        ["Choose a recording that still matters to you. That's a better starting point than making something just to fill a calendar."],
        "Bring back a video",
    ),
    (
        "camera_roll", "Reconnect · 2 / Find the raw material",
        "Before you record more, look here",
        "Your camera roll may already have the raw material.",
        "Try the footage you already have.",
        ["An answer from a call. A walkthrough you recorded for one person. A useful moment from a longer take.",
         "Look for a section that would help someone else without needing the whole recording around it. Upload footage you have permission to use, then give Valmera the context."],
        "Help me turn this explanation into a standalone clip. Keep enough context to make the answer clear.",
        ["Watch the result before exporting. The useful idea matters more than how recently you recorded it."],
        "Use an existing recording",
    ),
    (
        "open_door", "Reconnect · 3 / An open door",
        "For the next time you think “I should edit that”",
        "Keep this prompt for a recording that deserves a finished version.",
        "A starting point for later.",
        ["Maybe the next video isn't this week's job. When a recording does come along that you want to finish, here's a brief you can keep:"],
        "Help me make a clear, focused version of this video. Suggest the strongest section, keep its context, and wait for me to choose before editing.",
        ["Open Valmera when you have the footage and a reason to use it. We'll leave this return sequence here; you can unsubscribe from product emails below whenever you like."],
        "Open the studio",
    ),
]

# One recipe per scheduled slot. Successful send history decides the next
# recipe per recipient, so missed slots do not skip content for that person.
WEEKLY_COPY = [
    (
        "weekly_value", "Editing note · 01 / The opening",
        "Your opening might be hiding halfway through",
        "Look for the sentence that gives someone a reason to keep watching.",
        "Start where it gets interesting.",
        ["Introductions are useful while you're recording. In an edit, the strongest opening may arrive after you've warmed up.",
         "Find the sentence that states the useful idea, asks the real question, or shows the result. See how the video feels when that arrives sooner."],
        "Suggest a stronger opening using footage that's already here. Keep the context accurate, and show me your suggestion before changing the edit.",
        ["A good opening makes a clear promise. Keep watching the rest of the cut to check that it delivers."],
        "Find the opening",
    ),
    (
        "tip_pacing", "Editing note · 02 / Natural pacing",
        "Keep the breath. Lose the wait.",
        "Tighter pacing works best when the speaker still sounds human.",
        "Every pause isn't dead air.",
        ["A pause before a useful point can help it land. A long gap while someone searches for the next sentence may simply slow the video down.",
         "Give the editor that distinction instead of asking it to remove every silence."],
        "Trim long pauses and repeated starts. Keep natural breaths and pauses that help the point land.",
        ["Listen to the transitions in the preview. If a cut feels rushed, ask for more room around that sentence."],
        "Tighten the pacing",
    ),
    (
        "tip_captions", "Editing note · 03 / Readable captions",
        "Would you read these captions on a bus?",
        "Make the words easy to follow on a small screen.",
        "Give the words room to work.",
        ["Small type, long lines, and captions across someone's face make a video harder to follow. Start with readability before choosing an elaborate style."],
        "Add clear, high-contrast captions. Keep the lines short and position them away from the speaker's face.",
        ["Review names, numbers, and specialist terms against the audio. Then watch at phone size to judge the placement."],
        "Check my captions",
    ),
    (
        "tip_vertical", "Editing note · 04 / Vertical framing",
        "Vertical is more than a crop",
        "Keep the action, the face, and the useful detail in view.",
        "What's the frame supposed to show?",
        ["A wide shot can become a useful vertical video, but only if the important detail survives. A face, a pair of hands, and a product demonstration need different framing decisions."],
        "Reframe this for 9:16. Keep the speaker and the important demonstration in view. Flag any section where the crop loses useful detail.",
        ["Watch the whole preview. Pay particular attention when the speaker moves or holds something up."],
        "Review a vertical cut",
    ),
    (
        "tip_music", "Editing note · 05 / Music underneath",
        "The music should know who's talking",
        "Let the soundtrack support the voice instead of competing with it.",
        "Let the voice lead.",
        ["A track can set the mood and still make the video harder to understand. Start quietly, then listen where the speaker gets softer."],
        "Add a subtle background track from the music library and keep it low under the voice.",
        ["Preview on the speakers you normally use. If you have to concentrate to hear a sentence, ask to lower the music there."],
        "Balance the soundtrack",
    ),
    (
        "tip_broll", "Editing note · 06 / Useful B-roll",
        "Show the thing you're explaining",
        "Give the viewer something relevant to look at while the idea lands.",
        "Make the cutaway earn its place.",
        ["When someone describes a process or a product, a relevant shot can make the point clearer. Random decoration can pull attention away from it.",
         "Add your own supporting footage to the project and be specific about where it belongs."],
        "Use the supporting clip while I explain what it shows. Keep my voice playing underneath and return to the speaker afterward.",
        ["Check that the picture actually matches the claim being made. The cutaway should help someone understand."],
        "Add a useful cutaway",
    ),
    (
        "tip_demo", "Editing note · 07 / The demonstration",
        "Show me the result first",
        "Give your demo a destination before you explain the steps.",
        "A demonstration needs a payoff.",
        ["If the footage includes the finished result, try showing it near the beginning. Then walk through the steps someone needs to understand how you got there."],
        "Open with the finished result, then show the essential steps in order. Cut repeated explanations and keep the labels readable.",
        ["Review the sequence for missing context. Someone seeing the product for the first time should be able to follow it."],
        "Shape a clearer demo",
    ),
    (
        "tip_interview", "Editing note · 08 / One useful answer",
        "A whole interview. One useful answer.",
        "Build a clip around a question someone actually has.",
        "Keep the answer and its context.",
        ["A short interview clip needs to make sense without the conversation around it. Choose an answer that stands on its own, then keep enough of the question or setup to orient the viewer."],
        "Find a complete answer that could work as a standalone clip. Keep the context needed to understand it, and suggest the section before editing.",
        ["Listen for words like “that” and “it” whose meaning was explained earlier. Bring back the missing context if the cut needs it."],
        "Find a complete answer",
    ),
    (
        "tip_specific_feedback", "Editing note · 09 / Better feedback",
        "The most useful edit is often the second one",
        "Tell the editor exactly what the first preview helped you notice.",
        "React to something specific.",
        ["The first preview gives you evidence: an opening that drags, a caption that covers a detail, or a transition that arrives too quickly.",
         "Name the moment and the change you want. A precise follow-up is easier to review than asking for an entirely different video."],
        "Keep this version, but give the opening sentence more breathing room. Leave the music and caption style unchanged.",
        ["Use the actual moment you noticed in your own footage. Then check that the next preview fixes that point."],
        "Refine one moment",
    ),
    (
        "tip_soundoff", "Editing note · 10 / The silent review",
        "Mute your video. Does it still make sense?",
        "A simple review that reveals missing context and unreadable text.",
        "Try one silent viewing.",
        ["Watch the preview without sound. Can you tell what the video is about? Can you read the captions comfortably? Is an important point delivered only in the voiceover?"],
        "Add a short opening title that states what this video explains. Keep it clear of the captions and important action.",
        ["Turn the sound back on for the final review. The words, picture, and voice should all tell the same story."],
        "Try the silent review",
    ),
    (
        "tip_ending", "Editing note · 11 / A deliberate ending",
        "Give the last sentence somewhere to land",
        "Finish the thought before you finish the file.",
        "An ending deserves an edit too.",
        ["The recording may end with someone reaching for the camera or repeating the point. Your video can end where the thought is complete.",
         "Leave a little space after the last useful sentence so the cut feels intentional."],
        "End after the final useful point. Remove the recording cleanup at the end and leave a natural pause before the video finishes.",
        ["Watch the final few seconds again. If the video needs a next step, make it one that fits the message."],
        "Shape the ending",
    ),
    (
        "tip_one_idea", "Editing note · 12 / One idea",
        "What if this video only did one thing?",
        "Choose the point you'd want someone to remember tomorrow.",
        "Give the cut one clear job.",
        ["A recording can hold three useful ideas while the edit only needs one. Choose the point your audience came for, then check which sections help them understand it."],
        "Make a focused cut around the main idea. Keep the example that explains it and remove the unrelated tangents.",
        ["Keep your downloaded versions if you want to compare cuts. The other ideas may deserve separate edits of their own."],
        "Make a focused version",
    ),
]

WEEKLY_ORDER = [item[0] for item in WEEKLY_COPY]
CAMPAIGN_FAMILY = {
    key: family for family, keys in LIFECYCLE_FAMILIES.items() for key in keys
}
CAMPAIGN_LABELS = {item[0]: item[1] for item in LIFECYCLE_COPY + WEEKLY_COPY}
CAMPAIGN_LABELS["offer_50"] = "Retired · Introductory discount"

# Milestone first; useful scheduled lessons run before dormant/winback mail.
LIFECYCLE_ORDER = [
    key for family in ("first_export", "welcome_activation", "first_cut", "export_nudge", "dormant", "winback")
    for key in LIFECYCLE_FAMILIES[family]
]
