steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile
      - --target
      - worker-base
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
