"""The built-in sound-effects pack — clicks, whooshes, impacts, risers.

Users kept asking for the accents that carry short-form video ("add a whoosh
on that cut", "put a click there", "hit it with something"), and the agent had
nothing to reach for. Music alone cannot do this: an sfx is a transient at a
POINT, not a bed over a span.

WHY THESE ARE SYNTHESIZED, NOT SOURCED. They ship inside our image AND inside
customers' exported, often monetized, videos. That needs CC0 with no
attribution obligation — and the verifiably-CC0 sound pools are overwhelmingly
retro game-UI blips, which would make a Reels edit sound like an indie
platformer. "Royalty-free" licences almost universally permit use in a video
and FORBID redistributing the files inside software, which is exactly what
bundling is. So the pack is generated by worker/tools/build_sfx.py: whooshes
are band-passed noise sweeps, impacts are pitch-collapsing sines, risers are
rising filtered noise — which is how these sounds are produced in the first
place, not an approximation of a recording. We own every sample outright.

The honest weak spot is `shutter`: a real camera shutter is four mechanical
events whose realism lives in the micro-timing between them, and synthesis
only gets close. It is the one entry a recording would improve.

Resolution machinery and its security rationale live in bundled_library.py.
Read that before changing anything here.
"""

import bundled_library

# Plain-language groupings — the words users actually say, not a taxonomy.
CATEGORIES = ("ui", "transition", "impact", "riser", "alert")

_LIB = bundled_library.Library("sfx", "sfx", "category", CATEGORIES)

SCHEME = _LIB.scheme
SFX_DIR = _LIB.dir
# Each entry: slug, title, category, duration_s, file, license, author,
# source_url, tags.
CATALOG = _LIB.catalog

ref = _LIB.ref
is_library_ref = _LIB.is_ref
resolve = _LIB.resolve
local_path = _LIB.local_path
duration_of = _LIB.duration_of
browse = _LIB.browse


def describe(t):
    """One line per sound, as the agent sees it. Tags carry most of the
    matching value here — "whoosh" and "swipe" are the same gesture at
    different lengths, and the agent picks by what the user said."""
    bits = [f'"{t["title"]}"', t.get("category", "?")]
    if t.get("duration_s"):
        bits.append(f"{t['duration_s']:.2f}s")
    if t.get("tags"):
        bits.append(str(t["tags"]))
    return ", ".join(bits)
